apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: application
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Harishkumarnimmala/openshift-native-deployment-of-secure-scalable-automated-application.git
      ref: master
      contextDir: application-stack/application
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: application:latest
