apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Harishkumarnimmala/openshift-native-deployment-of-secure-scalable-automated-application.git
      contextDir: application-stack/backend
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
